"""Initial consolidated schema after reset (2025-08-25)

Revision ID: 20250825_0001
Revises:
Create Date: 2025-08-25 12:15:00.000000
"""
from collections.abc import Sequence

revision: str = "20250825_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def upgrade() -> None:
    # AUTOGENERATED CONTENT START (voorbeeld – jouw echte output zal alle tabellen bevatten)
    # op.create_table('locations', ...)
    # op.create_table('observation_hourly', ...)
    # op.create_index(...)
    # AUTOGENERATED CONTENT END
    pass

def downgrade() -> None:
    # Drop in reverse order
    # op.drop_table('observation_hourly')
    # op.drop_table('locations')
    pass
