"""add_location_groups_and_members

Revision ID: add_location_groups
Revises: 24d3fcd30cb4
Create Date: 2024-08-23 15:47:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import DateTime, Float, ForeignKey, Index, Integer, String, Text


# revision identifiers, used by Alembic.
revision = 'add_location_groups'
down_revision = '24d3fcd30cb4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create location_groups table
    op.create_table('location_groups',
        sa.Column('id', Integer(), nullable=False),
        sa.Column('user_id', Integer(), nullable=False),
        sa.Column('name', String(255), nullable=False),
        sa.Column('description', String(500), nullable=True),
        sa.Column('created_at', DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_groups_id'), 'location_groups', ['id'], unique=False)
    op.create_index('ix_location_groups_user_name', 'location_groups', ['user_id', 'name'], unique=False)

    # Create location_group_members table
    op.create_table('location_group_members',
        sa.Column('id', Integer(), nullable=False),
        sa.Column('group_id', Integer(), nullable=False),
        sa.Column('location_id', Integer(), nullable=False),
        sa.Column('added_at', DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['group_id'], ['location_groups.id'], ),
        sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_group_members_id'), 'location_group_members', ['id'], unique=False)
    op.create_index('ix_location_group_members_unique', 'location_group_members', ['group_id', 'location_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_location_group_members_unique', table_name='location_group_members')
    op.drop_index(op.f('ix_location_group_members_id'), table_name='location_group_members')
    op.drop_table('location_group_members')
    op.drop_index('ix_location_groups_user_name', table_name='location_groups')
    op.drop_index(op.f('ix_location_groups_id'), table_name='location_groups')
    op.drop_table('location_groups')
    # ### end Alembic commands ###